-- =====================================================
-- SAMPLE DATA
-- =====================================================

INSERT INTO AIRPORTS VALUES ('AP1','Delhi Airport','Delhi','India','DEL','VIDP');
INSERT INTO AIRPORTS VALUES ('AP2','Mumbai Airport','Mumbai','India','BOM','VABB');
INSERT INTO AIRPORTS VALUES ('AP3','Chennai Airport','Chennai','India','MAA','VOMM');
INSERT INTO AIRPORTS VALUES ('AP4','Kolkata Airport','Kolkata','India','CCU','VECC');
INSERT INTO AIRPORTS VALUES ('AP5','Hyderabad Airport','Hyderabad','India','HYD','VOHS');
INSERT INTO AIRPORTS VALUES ('AP6','Bangalore Airport','Bangalore','India','BLR','VOBL');
INSERT INTO AIRPORTS VALUES ('AP7','Pune Airport','Pune','India','PNQ','VAPO');
INSERT INTO AIRPORTS VALUES ('AP8','Goa Airport','Goa','India','GOI','VOGO');
INSERT INTO AIRPORTS VALUES ('AP9','Jaipur Airport','Jaipur','India','JAI','VIJP');
INSERT INTO AIRPORTS VALUES ('AP10','Lucknow Airport','Lucknow','India','LKO','VILK');


INSERT INTO AIRCRAFT VALUES ('AC1','A320','Airbus','180',1001);
INSERT INTO AIRCRAFT VALUES ('AC2','B737','Boeing','160',1002);
INSERT INTO AIRCRAFT VALUES ('AC3','A321','Airbus','200',1003);
INSERT INTO AIRCRAFT VALUES ('AC4','B777','Boeing','300',1004);
INSERT INTO AIRCRAFT VALUES ('AC5','ATR72','ATR','70',1005);


INSERT INTO AIRLINES VALUES ('AL1','Air India','AI','AIC','India');
INSERT INTO AIRLINES VALUES ('AL2','Indigo','6E','IGO','India');
INSERT INTO AIRLINES VALUES ('AL3','SpiceJet','SG','SEJ','India');
INSERT INTO AIRLINES VALUES ('AL4','Vistara','UK','VTI','India');
INSERT INTO AIRLINES VALUES ('AL5','GoAir','G8','GOW','India');


INSERT INTO FLIGHTS VALUES ('FL1','AL1','AI101','AP1','AP2','AC1');
INSERT INTO FLIGHTS VALUES ('FL2','AL2','6E202','AP2','AP3','AC2');
INSERT INTO FLIGHTS VALUES ('FL3','AL3','SG303','AP3','AP4','AC3');
INSERT INTO FLIGHTS VALUES ('FL4','AL4','UK404','AP4','AP5','AC4');
INSERT INTO FLIGHTS VALUES ('FL5','AL5','G8505','AP5','AP6','AC5');


INSERT INTO FLIGHT_SCHEDULE VALUES ('SCH1','FL1',SYSDATE,SYSDATE,'MON');
INSERT INTO FLIGHT_SCHEDULE VALUES ('SCH2','FL2',SYSDATE,SYSDATE,'TUE');
INSERT INTO FLIGHT_SCHEDULE VALUES ('SCH3','FL3',SYSDATE,SYSDATE,'WED');
INSERT INTO FLIGHT_SCHEDULE VALUES ('SCH4','FL4',SYSDATE,SYSDATE,'THU');
INSERT INTO FLIGHT_SCHEDULE VALUES ('SCH5','FL5',SYSDATE,SYSDATE,'FRI');


INSERT INTO DAILY_FLIGHT_STATUS VALUES ('DF1','SCH1',SYSDATE,'On Time',SYSDATE,SYSDATE);
INSERT INTO DAILY_FLIGHT_STATUS VALUES ('DF2','SCH2',SYSDATE,'Delayed',SYSDATE,SYSDATE);
INSERT INTO DAILY_FLIGHT_STATUS VALUES ('DF3','SCH3',SYSDATE,'On Time',SYSDATE,SYSDATE);
INSERT INTO DAILY_FLIGHT_STATUS VALUES ('DF4','SCH4',SYSDATE,'Cancelled',SYSDATE,SYSDATE);
INSERT INTO DAILY_FLIGHT_STATUS VALUES ('DF5','SCH5',SYSDATE,'On Time',SYSDATE,SYSDATE);


INSERT INTO PASSENGERS VALUES ('P1','Ram','Kumar','ram@mail.com',9876543210,'P1234');
INSERT INTO PASSENGERS VALUES ('P2','Amit','Shah','amit@mail.com',9876543211,'P1235');
INSERT INTO PASSENGERS VALUES ('P3','Ravi','Das','ravi@mail.com',9876543212,'P1236');
INSERT INTO PASSENGERS VALUES ('P4','Sita','Roy','sita@mail.com',9876543213,'P1237');
INSERT INTO PASSENGERS VALUES ('P5','Neha','Singh','neha@mail.com',9876543214,'P1238');


INSERT INTO BOOKING VALUES ('B1','P1',SYSDATE,5000,'Confirmed');
INSERT INTO BOOKING VALUES ('B2','P2',SYSDATE,4500,'Confirmed');
INSERT INTO BOOKING VALUES ('B3','P3',SYSDATE,5500,'Cancelled');
INSERT INTO BOOKING VALUES ('B4','P4',SYSDATE,6000,'Confirmed');
INSERT INTO BOOKING VALUES ('B5','P5',SYSDATE,4800,'Pending');


INSERT INTO TICKETS VALUES ('T1','B1','DF1','12A','Economy');
INSERT INTO TICKETS VALUES ('T2','B2','DF2','14B','Business');
INSERT INTO TICKETS VALUES ('T3','B3','DF3','10C','Economy');
INSERT INTO TICKETS VALUES ('T4','B4','DF4','16D','Economy');
INSERT INTO TICKETS VALUES ('T5','B5','DF5','18E','Business');


INSERT INTO CREW VALUES ('C1','Raj','Verma','Pilot','L1001');
INSERT INTO CREW VALUES ('C2','Anil','Khan','CoPilot','L1002');
INSERT INTO CREW VALUES ('C3','Sara','Ali','Cabin','L1003');
INSERT INTO CREW VALUES ('C4','John','Paul','Cabin','L1004');
INSERT INTO CREW VALUES ('C5','Maya','Rao','Cabin','L1005');


INSERT INTO CREW_ASSIGNMENTS VALUES ('A1','DF1','C1');
INSERT INTO CREW_ASSIGNMENTS VALUES ('A2','DF2','C2');
INSERT INTO CREW_ASSIGNMENTS VALUES ('A3','DF3','C3');
INSERT INTO CREW_ASSIGNMENTS VALUES ('A4','DF4','C4');
INSERT INTO CREW_ASSIGNMENTS VALUES ('A5','DF5','C5');


INSERT INTO GATES VALUES ('G1','AP1','T1',1);
INSERT INTO GATES VALUES ('G2','AP2','T1',2);
INSERT INTO GATES VALUES ('G3','AP3','T2',3);
INSERT INTO GATES VALUES ('G4','AP4','T2',4);
INSERT INTO GATES VALUES ('G5','AP5','T3',5);


INSERT INTO BOARDING_PASSES VALUES ('BP1','T1','G1',SYSDATE,'A');
INSERT INTO BOARDING_PASSES VALUES ('BP2','T2','G2',SYSDATE,'B');
INSERT INTO BOARDING_PASSES VALUES ('BP3','T3','G3',SYSDATE,'C');
INSERT INTO BOARDING_PASSES VALUES ('BP4','T4','G4',SYSDATE,'D');
INSERT INTO BOARDING_PASSES VALUES ('BP5','T5','G5',SYSDATE,'E');


INSERT INTO BAGGAGE VALUES ('BG1','T1','15','Loaded','TAG1');
INSERT INTO BAGGAGE VALUES ('BG2','T2','18','Loaded','TAG2');
INSERT INTO BAGGAGE VALUES ('BG3','T3','12','Pending','TAG3');
INSERT INTO BAGGAGE VALUES ('BG4','T4','20','Loaded','TAG4');
INSERT INTO BAGGAGE VALUES ('BG5','T5','10','Lost','TAG5');


INSERT INTO MAINTENANCE_LOG VALUES ('M1','AC1',SYSDATE,'Engine Check','Fixed','Ramesh');
INSERT INTO MAINTENANCE_LOG VALUES ('M2','AC2',SYSDATE,'Tyre Issue','Replaced','Suresh');
INSERT INTO MAINTENANCE_LOG VALUES ('M3','AC3',SYSDATE,'Oil Leak','Repaired','Mahesh');
INSERT INTO MAINTENANCE_LOG VALUES ('M4','AC4',SYSDATE,'Brake Issue','Fixed','Naresh');
INSERT INTO MAINTENANCE_LOG VALUES ('M5','AC5',SYSDATE,'Fuel Check','Checked','Ganesh');


COMMIT;
