
-- =====================================================
-- TABLE RELATIONSHIPS (AS PROVIDED)
-- =====================================================

1. AIRPORTS.AIRPORT_ID = FLIGHTS.ORIGIN_ID
2. AIRPORTS.AIRPORT_ID = FLIGHTS.DESTINATION_ID
3. AIRPORTS.AIRPORT_ID = GATES.AIRPORT_ID

4. AIRCRAFT.AIRCRAFT_ID = FLIGHTS.AIRCRAFT_ID
5. AIRCRAFT.AIRCRAFT_ID = MAINTENANCE_LOG.AIRCRAFT_ID

6. AIRLINES.AIRLINE_ID = FLIGHTS.AIRLINE_ID

7. FLIGHTS.FLIGHT_ID = FLIGHT_SCHEDULE.FLIGHT_ID

8. FLIGHT_SCHEDULE.SCHEDULE_ID = DAILY_FLIGHT_STATUS.SCHEDULE_ID

9. DAILY_FLIGHT_STATUS.DAILY_FLIGHT_ID = TICKETS.DAILY_FLIGHT_ID

10. DAILY_FLIGHT_STATUS.DAILY_FLIGHT_ID = CREW_ASSIGNMENTS.DAILY_FLIGHT_ID

11. TICKETS.TICKET_ID = BAGGAGE.TICKET_ID

12. BOOKING.BOOKING_ID = TICKETS.BOOKING_ID

13. BOOKING.PASSENGER_ID = PASSENGERS.PASSENGER_ID

14. CREW.CREW_ID = CREW_ASSIGNMENTS.CREW_ID

15. GATES.GATE_ID = BOARDING_PASSES.GATE_ID

16. BOARDING_PASSES.TICKET_ID = TICKETS.TICKET_ID


-- =====================================================
-- AIRPORT MANAGEMENT SYSTEM - QUERIES (ORACLE SQL)
-- =====================================================

-- 1. DISPLAY THE AIRPORT NAME, IT MUST BE DESTINATION OF PASSENGER, WITH THE PASSENGER MOBILE NUMBER 9876543211.

SELECT NAME
FROM AIRPORTS
WHERE AIRPORT_ID IN(SELECT DESTINATION_ID
FROM FLIGHTS
WHERE FLIGHT_ID IN(SELECT FLIGHT_ID
FROM FLIGHT_SCHEDULE
WHERE SCHEDULE_ID IN (SELECT SCHEDULE_ID
FROM DAILY_FLIGHT_STATUS
WHERE DAILY_FLIGHT_ID IN (SELECT DAILY_FLIGHT_ID
FROM TICKETS
WHERE BOOKING_ID IN(SELECT BOOKING_ID
FROM BOOKING
WHERE PASSENGER_ID IN (SELECT PASSENGER_ID
FROM PASSENGERS
WHERE PHONE_NUMBER = 9876543211))))));


-- 2. DISPLAY PASSENGER DETAILS WHO LANDED ON HYDERABAD AIRPORT ON 25-JAN-2026

SELECT *
FROM PASSENGERS
WHERE PASSENGER_ID IN (SELECT PASSENGER_ID
FROM BOOKING
WHERE BOOKING_ID IN (SELECT BOOKING_ID
FROM TICKETS
WHERE DAILY_FLIGHT_ID IN (SELECT DAILY_FLIGHT_ID
FROM DAILY_FLIGHT_STATUS
WHERE FLIGHT_DATE = '25-JAN-2026'AND SCHEDULE_ID IN (SELECT SCHEDULE_ID
FROM FLIGHT_SCHEDULE
WHERE FLIGHT_ID IN (SELECT FLIGHT_ID
FROM FLIGHTS
WHERE DESTINATION_ID IN (SELECT AIRPORT_ID
FROM AIRPORTS
WHERE CITY = 'Hyderabad'))))));


-- 3. FIND MODEL AND CAPACITY OF THE AIRCRAFT WHICH HAS HIGHEST CAPACITY

SELECT MODEL, CAPACITY
FROM AIRCRAFT
WHERE CAPACITY IN(SELECT MAX(CAPACITY)
FROM AIRCRAFT);

-- 4. NAME OF THE AIRPORT USED AS ORIGIN BUT NEVER AS DESTINATION

SELECT NAME
FROM AIRPORTS
WHERE AIRPORT_ID IN (SELECT ORIGIN_ID
FROM FLIGHTS)AND AIRPORT_ID NOT IN (SELECT DESTINATION_ID
FROM FLIGHTS
);


-- 5. THE AIRLINE NAME OPERATING THE MAXIMUM NUMBER OF FLIGHTS

SELECT NAME
FROM AIRLINES
WHERE AIRLINE_ID = (SELECT AIRLINE_ID
FROM FLIGHTS
GROUP BY AIRLINE_ID
HAVING COUNT(*) = (SELECT MAX(COUNT(*))
FROM FLIGHTS
GROUP BY AIRLINE_ID));


-- 6. FIND THE AIRPORT NAME THAT HAS NO SCHEDULE FLIGHTS

SELECT NAME
FROM AIRPORTS
WHERE AIRPORT_ID NOT IN (
SELECT ORIGIN_ID FROM FLIGHTS
UNION
SELECT DESTINATION_ID FROM FLIGHTS
);


-- =====================================================
-- ADVANCED QUERIES (ADDED)
-- =====================================================


-- 1. SAME QUERY USING JOINS (OPTIMIZED VERSION)

SELECT P.FIRST_NAME, P.LAST_NAME, A.NAME
FROM PASSENGERS P
JOIN BOOKING B ON P.PASSENGER_ID = B.PASSENGER_ID
JOIN TICKETS T ON B.BOOKING_ID = T.BOOKING_ID
JOIN DAILY_FLIGHT_STATUS D ON T.DAILY_FLIGHT_ID = D.DAILY_FLIGHT_ID
JOIN FLIGHT_SCHEDULE FS ON D.SCHEDULE_ID = FS.SCHEDULE_ID
JOIN FLIGHTS F ON FS.FLIGHT_ID = F.FLIGHT_ID
JOIN AIRPORTS A ON F.DESTINATION_ID = A.AIRPORT_ID
WHERE P.PHONE_NUMBER = 9876543211;


-- 2. TOTAL BOOKINGS PER AIRLINE

SELECT A.NAME, COUNT(*) TOTAL_BOOKINGS
FROM AIRLINES A
JOIN FLIGHTS F ON A.AIRLINE_ID = F.AIRLINE_ID
JOIN FLIGHT_SCHEDULE FS ON F.FLIGHT_ID = FS.FLIGHT_ID
JOIN DAILY_FLIGHT_STATUS D ON FS.SCHEDULE_ID = D.SCHEDULE_ID
JOIN TICKETS T ON D.DAILY_FLIGHT_ID = T.DAILY_FLIGHT_ID
GROUP BY A.NAME;


-- 3. TOTAL REVENUE FROM CONFIRMED BOOKINGS

SELECT SUM(TOTAL_AMOUNT) TOTAL_REVENUE
FROM BOOKING
WHERE STATUS = 'Confirmed';


-- 4. MOST ACTIVE AIRPORT (BY FLIGHTS)

SELECT A.NAME, COUNT(*) TOTAL_FLIGHTS
FROM AIRPORTS A
JOIN FLIGHTS F ON A.AIRPORT_ID = F.ORIGIN_ID
GROUP BY A.NAME
ORDER BY TOTAL_FLIGHTS DESC;


-- 5. PASSENGERS WITH MULTIPLE BOOKINGS

SELECT PASSENGER_ID, COUNT(*) BOOKINGS
FROM BOOKING
GROUP BY PASSENGER_ID
HAVING COUNT(*) > 1;


-- 6. DELAYED FLIGHTS

SELECT *
FROM DAILY_FLIGHT_STATUS
WHERE STATUS = 'Delayed';


-- 7. CREW ASSIGNED TO EACH FLIGHT

SELECT C.FIRST_NAME, C.LAST_NAME, D.DAILY_FLIGHT_ID
FROM CREW C
JOIN CREW_ASSIGNMENTS CA ON C.CREW_ID = CA.CREW_ID
JOIN DAILY_FLIGHT_STATUS D ON CA.DAILY_FLIGHT_ID = D.DAILY_FLIGHT_ID;


-- 8. PASSENGER WITH SEAT NUMBER AND CLASS

SELECT P.FIRST_NAME, T.SEAT_NUMBER, T.TICKET_CLASS
FROM PASSENGERS P
JOIN BOOKING B ON P.PASSENGER_ID = B.PASSENGER_ID
JOIN TICKETS T ON B.BOOKING_ID = T.BOOKING_ID;


-- 9. BAGGAGE STATUS PER PASSENGER

SELECT P.FIRST_NAME, BG.STATUS
FROM PASSENGERS P
JOIN BOOKING B ON P.PASSENGER_ID = B.PASSENGER_ID
JOIN TICKETS T ON B.BOOKING_ID = T.BOOKING_ID
JOIN BAGGAGE BG ON T.TICKET_ID = BG.TICKET_ID;


-- 10. AIRCRAFT USED IN MAXIMUM FLIGHTS

SELECT AIRCRAFT_ID, COUNT(*) TOTAL
FROM FLIGHTS
GROUP BY AIRCRAFT_ID
HAVING COUNT(*) = (
SELECT MAX(COUNT(*))
FROM FLIGHTS
GROUP BY AIRCRAFT_ID
);

-- 11. TOP 3 AIRLINES BASED ON NUMBER OF FLIGHTS

SELECT NAME, TOTAL_FLIGHTS
FROM (
    SELECT A.NAME, COUNT(*) TOTAL_FLIGHTS,
           RANK() OVER (ORDER BY COUNT(*) DESC) RANK_NO
    FROM AIRLINES A
    JOIN FLIGHTS F ON A.AIRLINE_ID = F.AIRLINE_ID
    GROUP BY A.NAME
)
WHERE RANK_NO <= 3;


-- 12. PASSENGERS WHO TRAVELLED IN BUSINESS CLASS

SELECT DISTINCT P.FIRST_NAME, P.LAST_NAME
FROM PASSENGERS P
JOIN BOOKING B ON P.PASSENGER_ID = B.PASSENGER_ID
JOIN TICKETS T ON B.BOOKING_ID = T.BOOKING_ID
WHERE T.TICKET_CLASS = 'Business';


-- 13. COUNT OF FLIGHTS PER DAY OF WEEK

SELECT DAYS_OF_WEEK, COUNT(*) TOTAL_FLIGHTS
FROM FLIGHT_SCHEDULE
GROUP BY DAYS_OF_WEEK;


-- 14. FIND PASSENGERS WHO HAVE NOT BOOKED ANY TICKETS

SELECT *
FROM PASSENGERS
WHERE PASSENGER_ID NOT IN (
    SELECT PASSENGER_ID FROM BOOKING
);


-- 15. FIND AIRCRAFT WHICH NEVER USED IN FLIGHTS

SELECT *
FROM AIRCRAFT
WHERE AIRCRAFT_ID NOT IN (
    SELECT AIRCRAFT_ID FROM FLIGHTS
);
