-- =====================================================
-- AIRPORT MANAGEMENT SYSTEM - SCHEMA (ORACLE SQL)
-- =====================================================


CREATE TABLE AIRPORTS
(
AIRPORT_ID CHAR(20) PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
CITY VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(20) NOT NULL,
IATA_CODE VARCHAR(20) UNIQUE NOT NULL,
ICAO_CODE VARCHAR(20) UNIQUE NOT NULL
);


CREATE TABLE AIRCRAFT
(
AIRCRAFT_ID CHAR(20) PRIMARY KEY,
MODEL VARCHAR(20) NOT NULL,
MANUFACTURE VARCHAR(20) NOT NULL,
CAPACITY VARCHAR(20) NOT NULL,
TAIL_NUMBER NUMBER(30) NOT NULL
);


CREATE TABLE AIRLINES
(
AIRLINE_ID CHAR(20) PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
IATA_CODE VARCHAR(20) NOT NULL,
ICAO_CODE VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(20) NOT NULL
);


CREATE TABLE FLIGHTS
(
FLIGHT_ID CHAR(30) PRIMARY KEY,
AIRLINE_ID CHAR(20) REFERENCES AIRLINES(AIRLINE_ID),
FLIGHT_NUMBER VARCHAR(20) UNIQUE NOT NULL,
ORIGIN_ID VARCHAR(20) NOT NULL,
DESTINATION_ID CHAR(20) NOT NULL,
AIRCRAFT_ID CHAR(20) REFERENCES AIRCRAFT(AIRCRAFT_ID)
);


CREATE TABLE FLIGHT_SCHEDULE
(
SCHEDULE_ID CHAR(20) PRIMARY KEY,
FLIGHT_ID CHAR(30) REFERENCES FLIGHTS(FLIGHT_ID),
DEPARTURE_TIME DATE NOT NULL,
ARRIVAL_TIME DATE NOT NULL,
DAYS_OF_WEEK VARCHAR(10) NOT NULL
);


CREATE TABLE DAILY_FLIGHT_STATUS
(
DAILY_FLIGHT_ID CHAR(20) PRIMARY KEY,
SCHEDULE_ID CHAR(20) REFERENCES FLIGHT_SCHEDULE(SCHEDULE_ID),
FLIGHT_DATE DATE NOT NULL,
STATUS VARCHAR(20) NOT NULL,
ACTUAL_DEPARTURE DATE NOT NULL,
ACTUAL_ARRIVAL DATE NOT NULL
);


CREATE TABLE PASSENGERS
(
PASSENGER_ID CHAR(20) PRIMARY KEY,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
PHONE_NUMBER NUMBER(20) NOT NULL,
PASSPORT_NUMBER VARCHAR(20) UNIQUE NOT NULL
);


CREATE TABLE BOOKING
(
BOOKING_ID CHAR(20) PRIMARY KEY,
PASSENGER_ID CHAR(20) REFERENCES PASSENGERS(PASSENGER_ID),
BOOKING_DATE DATE NOT NULL,
TOTAL_AMOUNT NUMBER(10,3) NOT NULL,
STATUS VARCHAR(20) NOT NULL
);


CREATE TABLE TICKETS
(
TICKET_ID CHAR(20) PRIMARY KEY,
BOOKING_ID CHAR(20) REFERENCES BOOKING(BOOKING_ID),
DAILY_FLIGHT_ID CHAR(20) REFERENCES DAILY_FLIGHT_STATUS(DAILY_FLIGHT_ID),
SEAT_NUMBER VARCHAR(20) NOT NULL,
TICKET_CLASS VARCHAR(20) NOT NULL
);


CREATE TABLE CREW
(
CREW_ID CHAR(20) PRIMARY KEY,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
ROLE VARCHAR(20) NOT NULL,
LICENSE_NUMBER VARCHAR(20) UNIQUE NOT NULL
);


CREATE TABLE CREW_ASSIGNMENTS
(
ASSIGNMENTS_ID CHAR(20) PRIMARY KEY,
DAILY_FLIGHT_ID CHAR(20) REFERENCES DAILY_FLIGHT_STATUS(DAILY_FLIGHT_ID),
CREW_ID CHAR(20) REFERENCES CREW(CREW_ID)
);


CREATE TABLE GATES
(
GATE_ID CHAR(20) PRIMARY KEY,
AIRPORT_ID CHAR(20) REFERENCES AIRPORTS(AIRPORT_ID),
TERMINAL VARCHAR(2) NOT NULL,
GATE_NUMBER NUMBER(2) NOT NULL
);


CREATE TABLE BOARDING_PASSES
(
BOARDING_PASS_ID CHAR(20) PRIMARY KEY,
TICKET_ID CHAR(20) REFERENCES TICKETS(TICKET_ID),
GATE_ID CHAR(20) REFERENCES GATES(GATE_ID),
BOARDING_TIME DATE NOT NULL,
ZONE VARCHAR(20) NOT NULL
);


CREATE TABLE BAGGAGE
(
BAGGAGE_ID CHAR(20) PRIMARY KEY,
TICKET_ID CHAR(20) REFERENCES TICKETS(TICKET_ID),
WEIGHT_KG VARCHAR(5) NOT NULL,
STATUS VARCHAR(20) NOT NULL,
TAG_NUMBER VARCHAR(20) UNIQUE NOT NULL
);


CREATE TABLE MAINTENANCE_LOG
(
LOG_ID VARCHAR(20) PRIMARY KEY,
AIRCRAFT_ID CHAR(20) REFERENCES AIRCRAFT(AIRCRAFT_ID),
MAINTENANCE_DATE DATE NOT NULL,
ISSUE_REPORTED VARCHAR(30),
ACTION_TAKEN VARCHAR(30),
TECHNICIAN_NAME VARCHAR(20) NOT NULL
);